# Generated by Django 5.2.7 on 2025-10-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='specialevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='specialevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='specialevent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='specialevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='assigned_pos',
            field=models.ManyToManyField(blank=True, to='core.posaccount'),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='qr_data',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specialevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
