# Generated by Django 5.2.7 on 2025-10-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_specialevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialevent',
            name='assigned_pos',
            field=models.ManyToManyField(blank=True, related_name='special_events', to='core.posaccount'),
        ),
    ]
